- .gitignore
- ioos_qc/config.py
- ioos_qc/qartod.py
- tests/test_config.py
- tests/test_qartod.py
Updates: `rate_of_change` and `flat_line` tests use time intervals instead of "counts". This makes the test more generic. For example, you can specify a rate of change threshold of `0.5 units/second` instead of `0.5 units/count` -- the latter requires either some data massaging beforehand, or threshold config specific to each data stream coming in.
Also, fixed a bug with `spike_test` when there are negative values, and allow for `QcConfig` test with no arguments.
> rate_of_change and flat_line tests use time intervals 

- ioos_qc/qartod.py
- tests/test_qartod.py
Split variable 'thresholds' into 'suspect_threshold' and 'fail_threshold'.
This is based on user feedback -- one of the most common questions was "what does `thresholds` mean?". Of course they could read the docs, but I think it's helpful to make it as easy to understand as possible with just a quick overview.
Before:
After:
> clarify thresholds for spike and flat_line

- conda-recipe/meta.yaml
- requirements.txt
- tests/requirements.txt
- tests/test_qartod.py
Dask brings in a LOT of extra dependencies, and isn't required for the library itself, so removing it from dependencies. It's still listed as a test dependency, but the tests will run even if it's not installed.
Diff of dependencies: https://www.diffchecker.com/zC6gypy8
Deps before:
```
backcall           conda-forge/noarch::backcall-0.1.0-py_0
blas               conda-forge/linux-64::blas-1.1-openblas
bokeh              conda-forge/linux-64::bokeh-1.0.4-py37_1000
bottleneck         conda-forge/linux-64::bottleneck-1.2.1-py37h3010b51_1001
bzip2              conda-forge/linux-64::bzip2-1.0.6-h14c3975_1002
ca-certificates    conda-forge/linux-64::ca-certificates-2018.11.29-ha4d7672_0
certifi            conda-forge/linux-64::certifi-2018.11.29-py37_1000
cftime …
```
> Remove dask as requirement

- docs/source/examples/QartodTestExample_WaterLevel.ipynb
- ioos_qc/config.py
- tests/test_config.py
Resolves https://github.com/ioos/ioos_qc/issues/15 for `QcConfig`.
Still outstanding: add option to generate aggregate flag for `NcQcConfig`. That will be in a separate PR.
> Add QcConfig.run option to generate agg flag

- ioos_qc/qartod.py
- tests/test_qartod.py
Replace zipn.any() call with zinp.count() when checking for non-masked depth inputs because zinp.any() will give a false negative for an array where all (non-masked) depths are zero.
Make the checks on the time and depth ranges include the minimum of each members configured range. Previously the maximum was included (<=) but the minimum was excluded (>). To be consistent with the handling of vspan, include both endpoints. (The QARTOD manuals indicate the endpoints are included for vspan.)
Add a fspan parameter to the configuration. Most of the relevant QARTOD manuals specify a climatology test that does not have a fail span, but the Ocean Optics Data QARTOD manual specifies a climatology test with both a valid span and a fail span. To handle this case, the climatology code should support …
> Climatology updates: bugfixes, add fspan parameter

- docs/source/examples/QartodTestExample_WaterLevel.ipynb
- ioos_qc/config.py
- ioos_qc/qartod.py
- tests/test_config.py
https://github.com/ioos/ioos_qc/pull/23 added a `gen_agg` argument to `QcConfig.run`
```
qc = QcConfig({'qartod': {
'gross_range_test': {
'fail_span': [0, 12],
},
'spike_test': {
'suspect_threshold': 3,
'fail_threshold': 10,
}
}})
inp = [-1, 0, 1, 2, 10, 3]
results = qc.run(
inp=inp,
gen_agg=True
)
```
While this works, it is not consistent with the general approach of defining all test configurations in the JSON/YAML object. 
This update moves the `aggregate` to the config object itself:
```
qc = QcConfig({'qartod': {
'gross_range_test': {
'fail_span': [0, 12],
},
'spike_test': {
'suspect_threshold': 3,
'fail_threshold': 10,
},
'aggregate': {}
}})
inp = [-1, 0, 1, 2, 10, 3]
r = qc.run(
inp=inp
)
```
See https://github.com/ioos/ioos_qc/issues/15
> Generate qartod aggregate flag based on config

- .travis.yml
- docs/source/examples/QartodTestExample_SalinityAttenuation.ipynb
- ioos_qc/qartod.py
- tests/test_qartod.py
- tests/test_qartod_performance.py
Exploring the idea of using `min_period` (minimum number of **seconds** in window required to calculate a result) instead of `min_obs` (minimum number of **observations** in window required to calculate a result).
I duplicated the notebook example and checked in the output, so you can view them alongside. This PR is to illustrate this idea, and should NOT be merged in as-is.
> attenuated signal: add `min_period` option (alternative to `min_obs`)

- ioos_qc/qartod.py
- tests/test_config.py
- tests/test_qartod.py
If `abs(inp[0])>threshold` or `abs(inp[-1]>threshold)`, then the test marked that value as QC FAIL. But the spike test is not really defined for the first or last values in the array. So always set those flags to QC unknown.
> spike test bugfix: first & last values are unknown

- ioos_qc/qartod.py
- tests/test_qartod.py
This PR present an implementation of the spike detection algorithm presented within the issue #48 .
This Pull Request essentially add an optional input method to the QARTOD spike test that and add an optional differential method for detecting spikes. If not specified, the standard method average method suggested by QARTOD is used.
A series of tests are also added to the test module to handle the different methods and the method input.
> QARTOD Spike Test: alternative differential method 

- ioos_qc/qartod.py
- tests/test_qartod.py
Fixed issue in spike_test where the ref array was not getting initialized as a masked array. This was causing some values that should result in a masked restult to use the underlying value stored in the masked array to be using in the calculation resulting in incorrect results.
For example, with the following input:
[101, 102, --, 104, 105]
The resulting output should be:
[2, 9, 9, 9, 2]
However, with the ref array initialized as a non masked array the following is the result:
[2, 1, 9, 9, 2]
The affected tests were also updated to reflect the correct behavior.
> Fixed spike test masked array issue

- .pre-commit-config.yaml
- ioos_qc/utils.py
- requirements.txt
- setup.cfg
Geographiclib is a stable, well maintained, and pure python library. We only use pyproj here for the great_distance calculation, so we should be OK with this change.
The results are similar and geographiclib algorithms do not [suffer from this issue](https://github.com/axiom-data-science/pygc/issues/4). See for a poor man's comparison https://nbviewer.org/gist/ocefpaf/7d290f94e5ffec1af560ded41d8c0dd1
Closes #72.
PS: only the doc build is failing. That should be fixed in #73.
> Use geographiclib in lieu of pyproj

- docs/source/releases.rst
- docs/source/usage.rst
This fixes the ambiguity in some references, for example in the `release.rst` file all refs started with `Added` but this PR adds 1 more word to the reference make them different.
> disambiguate and fix some indentations

- ioos_qc/config_creator/config_creator.py
- requirements.txt
- setup.cfg
@kwilcox I believe we were relying on a bug and passing  an empty `y` to `CubicSpline` should return a `ValuError` but instead we just moved the iteration forward. This PR passes zeroes to ensure we have finite elements to start the iteration.
> Attempt to fix issue 86

- .pre-commit-config.yaml
Flake8 moved from gitlab to github
https://github.com/PyCQA/flake8
https://www.reddit.com/r/Python/comments/yvfww8/flake8_took_down_the_gitlab_repository_in_favor/
> correct link to flake8 on github

- ioos_qc/qartod.py
- requirements-dev.txt
> remove mamba's pin

- .pre-commit-config.yaml
- ioos_qc/qartod.py
- tests/test_qartod.py
Copied changes from https://github.com/ioos/ioos_qc/pull/104. Added a test to replicate missing values and no `zspan` set scenario https://github.com/ioos/ioos_qc/issues/65#issuecomment-1033141944. Proposed fix is to set MISSING flag at the end of `check()` so it doesn't get overridden by the GOOD flag. 
* Added new test `QartodClimatologyMissingTest` to `test_qartod.py` to capture scenario described in #65. The scenario is when a user passes an array with a missing data point (which gets masked by `ioos_qc`) and does not set `zspan` (depth range). The result is that the missing value gets flagged w/ 1 (GOOD) instead of 9 (MISSING). 
* `qartod.py` - the change is moving where we set the MISSING flag to the bottom of the `check()` function so that it doesn't get overridden when we set the …
> Climatology Test: Handing masked depths without zspan

- ioos_qc/qartod.py
This is a follow-up PR related to #107. 
While working on #107 I noticed that we were overwriting the MISSING data flag with a GOOD data flag. The #107 PR implemented a fix that is more of a bandaid that created the desired output, but doesn't address the underlying undesired behavior. 
The undesired behavior was occurring because we weren't using the masked array `inp` to create `z_idx`. See thread: https://github.com/ioos/ioos_qc/pull/107#discussion_r1546310270. @kthyng helped find the fix for this change!
I also put `flag_arr[inp.mask] = QartodFlags.MISSING` back where it was because I think we should be made aware if the underlying code is not working as expected (e.g. if newer `numpy` package versions changed the way masked arrays behave).
> Climatology Missing Values Test: Use masked array data and mask to create z_idx

- .github/workflows/tests.yml
Numba is available up to Python 3.12 and we should be able to test against all supported Python versions now.
> Test against latest python

- CONTRIBUTING.md
> created contributing.md

- requirements.txt
Numpy version should be less than 2 until we can fix the breaking changes.
> numpy version updated

- ioos_qc/axds.py
- ioos_qc/config.py
- ioos_qc/config_creator/config_creator.py
- ioos_qc/config_creator/get_assets.py
- ioos_qc/qartod.py
- ioos_qc/results.py
- ioos_qc/stores.py
- ioos_qc/streams.py
- ioos_qc/utils.py
- ruff.toml
- tests/test_config_creator.py
- tests/test_performance.py
- tests/test_qartod.py
Lots of churn but I'm almost done. I'm restricting to ruff checks that can surface bugs for now. Leaving some, like code complexity and documentation, for the future.
> Ruff-ALL streams.py

- .github/workflows/deploy-docs.yml
- .github/workflows/tests.yml
- requirements-dev.txt
> default shell

- ioos_qc/qartod.py
- requirements.txt
Looks like the new `np,ptp` will always return NaNs, even for a masked array :-/
I'm using `np.ma` in `std` as well to be on the safe side.
> Fix for numpy 2.0

- ioos_qc/qartod.py
- tests/test_qartod.py
Related to issue #106 
As per the observations:
**1. Diff results:**
Here are the diff results calculated using the average method:
```
[35.54251562117366 -- -- 0.0009809673153213794 0.0004743669231928038
0.0022776381135756196 -- -- -- 4.972008905212988e-05 0.007755656380723508
0.008936353381891138 0.001787683444078425]
```
**2. Flags Assigned:**
The flags based on these diff results are:
`[2 9 9 1 1 1 9 9 9 1 1 1 1]`
It appears that the flags are assigned correctly.
**3. Code for Examining Flags:**
**examining the spike test flag arrays**
```
wf = pd.DataFrame(x, flag_arr, ['salinity'])
print('right column KEYS: ', 'Missing', QartodFlags.MISSING, 'UNKNOWN', QartodFlags.UNKNOWN, '\n')
print(wf)
```
**4. Data and Flags Analysis:**
original dataset x
```
[35.54251562117366 -- …
```
> Fix flagging logic for missing and unknown data in QARTOD spike test

- ioos_qc/qartod.py
Looks like this  `**kwargs` is not used in the function. Removing it and merging this if the tests passes.
> Remove unused kw

- .github/workflows/pypi.yml
The publication worked even with this error. No need for a new release.
> fix copy-n-pasta
